CFG_SET 0, 0    # CSR[0] = DRAM_IFMAP_BASE
CFG_SET 1, 1    # CSR[1] = DRAM_WEIGHT_BASE
CFG_SET 2, 2    # CSR[2] = DRAM_OFMAP_BASE
CFG_SET 3, 3    # GLB_IFMAP_BASE
CFG_SET 4, 4    # GLB_WEIGHT_BASE
CFG_SET 5, 5    # GLB_OPSUM_BASE
CFG_SET 6, 6    # OF_SIZE
CFG_SET 7, 7    # IF_SIZE
CFG_SET 8, 8    # B_SIZE
CFG_SET 9, 9    # K_SIZE
CFG_SET 10,10   # N_SIZE
CFG_SET 11,11   # M_SIZE
CFG_SET 12,12   # DATA_FLOW

DMA_LOAD_WEIGHT DRAM_WEIGHT_BASE, 0, 2304
WAIT DMA
NOP
DMA_LOAD_IFMAP DRAM_IFMAP_BASE, 0, 72
WAIT DMA
NOP
DMA_LOAD_PSUM DRAM_OFMAP_BASE, 0, 128
WAIT DMA
NOP
DMA_STORE_OFMAP DRAM_OFMAP_BASE, 0, 128
WAIT DMA
NOP
END
