CFG_SET DRAM_IFMAP_BASE,     0
CFG_SET DRAM_WEIGHT_BASE,    1
CFG_SET DRAM_OFMAP_BASE,     2
DMA_LOAD_WEIGHT DRAM_WEIGHT_BASE, 0, 64
DMA_LOAD_IFMAP DRAM_IFMAP_BASE, 0, 64
DMA_LOAD_PSUM DRAM_OFMAP_BASE, 0, 64
DMA_STORE_OFMAP DRAM_OFMAP_BASE, 0, 64
END
