CPT_TAGXY IFMAP
LOADI r1, 0
G2P GLB_IFMAP_BASE, r1, 72   # GLB_IFMAP_BASE
WAIT GLB

CPT_TAGXY WEIGHT
LOADI r2, 0
G2P GLB_WEIGHT_BASE, r2, 2304
WAIT GLB

CPT_TAGXY IPSUM
LOADI r3, 0
G2P GLB_OPSUM_BASE, r3, 128
WAIT GLB

CPT_TAGXY OPSUM
LOADI r4, 0
P2G_OPSUM GLB_OPSUM_BASE, r4, 128
WAIT GLB
END